# Oscar Dominguez

In [1]:
# imports
import pandas as pd

# Numpy
import numpy as np

# Open saved file and preview again
sh_info_df = pd.read_csv("Data/superhero_info - superhero_info.csv", low_memory = False)
sh_info_df.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

# First dataframe

In [2]:
sh_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB

## Duplicates

In [3]:
#Printing duplicates
print(f'There are {sh_info_df.duplicated().sum()} duplicate rows.')

There are 0 duplicate rows.

## Missing values

In [4]:
#Printing duplicates
print(f'There are {sh_info_df.duplicated().sum()} duplicate rows.')

There are 0 duplicate rows.

In [5]:
# Example 4: Split single column into two columns use apply()
# Resource - https://sparkbyexamples.com/pandas/pandas-split-column/
sh_info_df[['Hero', 'Publisher']] \
= sh_info_df["Hero|Publisher"].apply(lambda x: pd.Series(str(x).split("|")))      

sh_info_df.drop("Hero|Publisher", axis = 1, inplace = True)

sh_info_df

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics
...,...,...,...,...,...,...,...,...,...
458,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}",Yellowjacket,Marvel Comics
459,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}",Yellowjacket II,Marvel Comics
460,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}",Yoda,George Lucas
461,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}",Zatanna,DC Comics
462,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}",Zoom,DC Comics

In [6]:
# create 2 new columns, FirstName and LastName by splitting the Name column
sh_info_df[['height cm','weight kg']] = sh_info_df['Measurements'].str.split(',', expand=True)
# drop the 'Name' column
sh_info_df.drop('Measurements', axis=1, inplace=True)
sh_info_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,height cm,weight kg
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,{'Height': '203.0 cm','Weight': '441.0 kg'}
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,{'Height': '191.0 cm','Weight': '65.0 kg'}
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,{'Height': '185.0 cm','Weight': '90.0 kg'}
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,{'Height': '203.0 cm','Weight': '441.0 kg'}
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,{'Height': '193.0 cm','Weight': '122.0 kg'}

In [7]:
# Resource - 
# https://stackoverflow.com/questions/13682044/remove-unwanted-parts-from-strings-in-a-column

sh_info_df["height cm"] = sh_info_df["height cm"].\
    map(lambda x: x.lstrip("{'Height': '").rstrip("cm'"))
sh_info_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,height cm,weight kg
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,'Weight': '441.0 kg'}
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,'Weight': '65.0 kg'}
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,'Weight': '90.0 kg'}
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,'Weight': '441.0 kg'}
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,'Weight': '122.0 kg'}

In [8]:
# Resource -
# https://stackoverflow.com/questions/13682044/remove-unwanted-parts-from-strings-in-a-column
sh_info_df["weight kg"] = sh_info_df["weight kg"].\
    map(lambda x: x.lstrip("'Weight': '").rstrip("kg'}"))
sh_info_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,height cm,weight kg
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0

In [9]:
sh_info_df = sh_info_df.astype({'height cm':'float'})
sh_info_df.dtypes

Gender         object
Race           object
Alignment      object
Hair color     object
Eye color      object
Skin color     object
Hero           object
Publisher      object
height cm     float64
weight kg      object
dtype: object

In [10]:
sh_info_df = sh_info_df.astype({'weight kg':'float'})
sh_info_df.dtypes

Gender         object
Race           object
Alignment      object
Hair color     object
Eye color      object
Skin color     object
Hero           object
Publisher      object
height cm     float64
weight kg     float64
dtype: object

# Second dataframe

In [11]:
sh_powers_df = pd.read_csv("Data/superhero_powers - superhero_powers.csv", low_memory = False)
sh_powers_df.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [12]:
 #Checking missing values and then I will impute Age and BP columns. I will then Ordinal Encode BP.
 sh_powers_df.isna().sum()

hero_names    0
Powers        0
dtype: int64

In [13]:
sh_powers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

## Duplicates

In [14]:
#Printing duplicates
print(f'There are {sh_powers_df.duplicated().sum()} duplicate rows.')

There are 0 duplicate rows.

## Missing values

In [15]:
#Printing duplicates
print(f'There are {sh_powers_df.duplicated().sum()} duplicate rows.')

There are 0 duplicate rows.

In [16]:
## showing the lists are really strings
sh_powers_df.loc[2,'Powers']

'Agility,Accelerated Healing,Cold Resistance,Durability,Underwater breathing,Marksmanship,Weapons Master,Longevity,Intelligence,Super Strength,Telepathy,Stamina,Immortality,Reflexes,Enhanced Sight,Sub-Mariner'

In [17]:
sh_powers_df_split = sh_powers_df['Powers'].str.split(',',expand=True)
sh_powers_df_split

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,Agility,Super Strength,Stamina,Super Speed,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,Accelerated Healing,Durability,Longevity,Super Strength,Stamina,Camouflage,Self-Sustenance,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,Agility,Accelerated Healing,Cold Resistance,Durability,Underwater breathing,Marksmanship,Weapons Master,Longevity,Intelligence,Super Strength,...,None,None,None,None,None,None,None,None,None,None
3,Lantern Power Ring,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,Accelerated Healing,Intelligence,Super Strength,Stamina,Super Speed,Invulnerability,Animation,Super Breath,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,Flight,Energy Blasts,Size Changing,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
663,Cold Resistance,Durability,Longevity,Super Strength,Cryokinesis,Immortality,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
664,Agility,Stealth,Danger Sense,Marksmanship,Weapons Master,Longevity,Intelligence,Telepathy,Energy Blasts,Stamina,...,None,None,None,None,None,None,None,None,None,None
665,Cryokinesis,Telepathy,Magic,Fire Control,Probability Manipulation,Water Control,Terrakinesis,Weather Control,None,None,...,None,None,None,None,None,None,None,None,None,None
666,Super Speed,Intangibility,Time Travel,Time Manipulation,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [18]:
# # Make a list of all characters to replace
# to_replace = ['(',')']
# # run a loop to replace all of the characters in the list at once
# for char in to_replace:
#     sh_powers_df['Powers'] = sh_powers_df['Powers'].str.replace(char,'',regex=False)
    
# sh_powers_df['Powers'].head()

In [19]:
# Resource - https://pandas.pydata.org/docs/user_guide/merging.html
frames = [sh_info_df ,sh_powers_df, sh_powers_df_split]

result = pd.concat(frames)
result

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,height cm,weight kg,...,39,40,41,42,43,44,45,46,47,48
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
663,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None

# Compare the average weight of super powers who have Super Speed to those who do not.

# What is the average height of heroes for each publisher?

In [20]:
budget_per_certification = result.groupby('Publisher')['height cm'].mean()
budget_per_certification

Publisher
DC Comics            181.923913
Dark Horse Comics    176.909091
George Lucas         159.600000
Image Comics         211.000000
Marvel Comics        191.546128
Shueisha             171.500000
Star Trek            181.500000
Team Epic TV         180.750000
Unknown              178.000000
Name: height cm, dtype: float64